### ISSUE TITLE
Programatically check the checkbox

### ISSUE THREAD

**Issue by InToSSH** [rogeriotaques/switchable#1]
Hi,
is there a way to programatically check the checkbox? If I do it on the input only, the switchable does not get checked.

For now I am using this function
```
function checkSwitchable(element, checked) {

    if (checked) {
        $(element).attr('checked', true);
        $(element).next('.switchable-wrapper').children('.switchable-holder').addClass('switchable-checked');
    } else {
        $(element).attr('checked', false);
        $(element).next('.switchable-wrapper').children('.switchable-holder').removeClass('switchable-checked');
    }
}
```

**Comment by rogeriotaques** [comment]
Hi, @InToSSH !

That's a good question! The short answer is no! Unfortunately, there's no methods in the current version to allow you programmatically check or uncheck the switcher. Sorry.

They way you're doing it seems to work pretty well. Good job.

It would be a great idea to implement that method, but I won't have time to do it in a short term. If you can do it, just PR it and I'd be very glad on merging the code. :)

**Comment by nashcsshtml** [comment]
Hello,

Downloaded your zip, and try your code for click :
<script type="text/javascript" >
	  $(document).ready(function(){
	    $('#myswitch').switchable({
            click: function( ev, checked )
            {
                console.log( ev.switcher.attr('id') );
            }
        });
	  });
	</script>
And i get the error :
TypeError: ev.switcher is undefined

**Comment by InToSSH** [comment]
Hi @nashcsshtml ,
I just tried to copy your code into my project and it works just fine. 
Make sure you have the required jQuery version or newer (min. v1.9).
Also next time you post a code we would really appreciate if you could use the correct github tag for code to keep the format and make it more readable. 😄

**Comment by rogeriotaques** [comment]
Hi, @nashcsshtml! As @InToSSH has mentioned, the code you've passed in your message is working well. Please follow InToSSH advice. 

Btw, @InToSSH I'm closing this issue. But feel free to reopen it or reach me anytime if you need. :)

**Comment by nashcsshtml** [comment]
Hello @InToSSH  @rogeriotaques ,
Sorry to bother again, i have updated jquery to version above 2. But still getting the same error. Here is a small zip.
[testSwitch.zip](https://github.com/rogeriotaques/switchable/files/1501756/testSwitch.zip)

**Comment by InToSSH** [comment]
Hi @nashcsshtml ,
checked your code, it is fine, the problem is that you are using the minified version of switchable, which I guess doesn't pass this property to the event var. As soon as you change your source from minified to standard version it will work. I am not using the minified version because I am combining all sources and minifiing them at once using Gulp. Not sure if this is intended or error in min version but you can always minify the full version yourself.

BTW sorry @rogeriotaques still didn't have some time to go through your code to include the programatical switch, but I will do it some time, if someone is not faster than me :smile:

**Comment by nashcsshtml** [comment]
Great thanks for the info @InToSSH

**Comment by rogeriotaques** [comment]
Thanks @InToSSH, no rush! Btw, good catch about the minified version. If I can find a time before you do it, I’ll implement that and fix the minified version as well.

**Comment by nashcsshtml** [comment]
@InToSSH @rogeriotaques ,
Sorry to bother again. I have a issue on samsung phones, the swipe does not work. Any workaround?

Regards.

**Comment by InToSSH** [comment]
@nashcsshtml well, simple click on the checkbox works on Samsung, just tested on my SGS8+ in Chrome. If you want to enable swipe left/right across the checkbox, you would have to use some other library to detect swipes, for example this one [TouchSwipe](https://github.com/mattbryson/TouchSwipe-Jquery-Plugin). Then use my code at the top to programatically check/uncheck the switchable checkbox. However you won't be able to actually manually drag the "bullet" inside the checkbox, but it should still look good.
